import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

/* ── Embedded fallback products (same data as /api/products) ── */
const FALLBACK_PRODUCTS = [
  { id:'fp-1', name:'GE Revolution CT Scanner', slug:'ge-revolution-ct-scanner', category:'CT', parentCategory:'Imaging Equipment', subCategory:'CT', condition:'Refurbished', price:185000, description:'The GE Revolution CT Scanner delivers exceptional image quality with its 256-slice detector and advanced iterative reconstruction technology. Designed for high-volume imaging centers, it provides fast turnaround times and reduced dose for patients. This refurbished unit has been fully inspected and calibrated to meet OEM specifications. Ideal for cardiac, neurological, and trauma imaging applications. Comes with a 12-month warranty and on-site installation support.', specs:'{"Detector Rows":"256 slices","Rotation Time":"0.28s","Slice Thickness":"0.625 mm","Gantry Aperture":"80 cm","Table Weight Limit":"450 lbs","Tube Heat Capacity":"8.0 MHU","Spatial Resolution":"0.24 mm","Software Version":"Revolution EVO"}', features:'["256-slice detector for superior image quality","Advanced iterative reconstruction (ASiR-V)","Low-dose cardiac CT angiography","One-beat cardiac imaging","Automated workflow with kV assist","Smart collimation for dose optimization"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:true, createdAt:'2025-01-15T10:00:00.000Z' },
  { id:'fp-2', name:'Siemens Magnetom Vida 3T MRI', slug:'siemens-magnetom-vida-3t-mri', category:'MRI', parentCategory:'Imaging Equipment', subCategory:'MRI', condition:'Refurbished', price:425000, description:'The Siemens Magnetom Vida 3T MRI combines Tim 4G and Dot technology to deliver outstanding diagnostic confidence across all clinical applications. Its 70 cm bore provides exceptional patient comfort while maintaining high-field performance. This refurbished system features the BioMatrix technology that personalizes exams for each patient. Perfect for neurology, orthopedics, and oncology imaging. Includes comprehensive installation and training package.', specs:'{"Field Strength":"3.0 Tesla","Bore Size":"70 cm","Gradient Strength":"45 mT/m","Slew Rate":"200 T/m/s","Channels":"up to 128","Coils":"18-element Body, Head/Neck, Spine","Patient Weight Limit":"550 lbs","Software":"syngo MR XA30"}', features:'["Tim 4G integrated coil technology","BioMatrix patient-personalized imaging","70 cm patient-friendly bore","Quiet Suite for reduced acoustic noise","Dot workflow automation","Advanced diffusion and perfusion imaging"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:true, createdAt:'2025-01-20T10:00:00.000Z' },
  { id:'fp-3', name:'Philips IU Elite Ultrasound', slug:'philips-iu-elite-ultrasound', category:'Ultrasound', parentCategory:'Imaging Equipment', subCategory:'Ultrasound', condition:'New', price:95000, description:'The Philips IU Elite Ultrasound system is a premium shared-service platform designed for exceptional clinical performance. It features advanced imaging technologies including nSIGHT imaging for enhanced tissue differentiation and PureWave crystal technology for superior resolution. The system excels in abdominal, vascular, OB/GYN, and musculoskeletal imaging.', specs:'{"Transducer Ports":"4 active ports","Display":"21.5 HD LCD","Imaging Modes":"B-mode, M-mode, Doppler, Harmonic","Tissue Harmonic":"nSIGHT","Frame Rate":"Up to 300 fps","Storage":"1 TB HDD + DVD-RW","Connectivity":"DICOM 3.0, USB, Ethernet","Weight":"325 lbs"}', features:'["nSIGHT imaging for enhanced tissue characterization","PureWave transducer technology","AutoSCAN for automated image optimization","Active Array matrix transducers","QLAB quantitative analysis","iSCAN one-touch image optimization"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:true, createdAt:'2025-02-01T10:00:00.000Z' },
  { id:'fp-4', name:'Zeiss Cirrus HD-OCT 6000', slug:'zeiss-cirrus-hd-oct-6000', category:'Ophthalmology', parentCategory:'Ophthalmology Equipment', subCategory:'OCT', condition:'New', price:75000, description:'The Zeiss Cirrus HD-OCT 6000 is the gold standard in optical coherence tomography for ophthalmic diagnostics. It provides ultra-high resolution retinal imaging with advanced segmentation algorithms for retinal nerve fiber layer and ganglion cell analysis.', specs:'{"Scan Speed":"68,000 A-scans/second","Axial Resolution":"5 \u03bcm","Transverse Resolution":"15 \u03bcm","Scan Depth":"2.0 mm","Scan Width":"9.0 mm","Imaging Modes":"Macula, Optic Disc, Anterior Segment, HD Angio","Eye Tracking":"TruTrack active","Display":"24 widescreen monitor"}', features:'["Ultra-high speed HD imaging","Advanced ganglion cell analysis (GCC)","Glaucoma progression analysis (GPA)","Anterior segment OCT module","HD Angio retinal vasculature imaging","Seamless EMR integration"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:true, createdAt:'2025-02-10T10:00:00.000Z' },
  { id:'fp-5', name:'Toshiba Aquilion ONE CT', slug:'toshiba-aquilion-one-ct', category:'CT', parentCategory:'Imaging Equipment', subCategory:'CT', condition:'Refurbished', price:210000, description:'The Toshiba Aquilion ONE CT Scanner features a 320-row detector that can image an entire organ in a single rotation, reducing motion artifacts and radiation dose significantly. Its cone-beam CT technology eliminates helical artifacts for pure volumetric imaging.', specs:'{"Detector Rows":"320 rows (0.5 mm)","Detector Coverage":"16 cm","Rotation Time":"0.275s","Slice Thickness":"0.5 mm","Gantry Aperture":"78 cm","Spatial Resolution":"0.35 mm","Tube Voltage":"80-135 kV","Software":"Vitrea workstation included"}', features:'["Volume CT with 16 cm coverage","Single-rotation whole-organ imaging","Ultra-low dose with AIDR 3D","Cardiac CT with 100% phase coverage","Brain perfusion in single rotation","Real-time image reconstruction"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-02-15T10:00:00.000Z' },
  { id:'fp-6', name:'Hitachi Echelon Oval MRI', slug:'hitachi-echelon-oval-mri', category:'MRI', parentCategory:'Imaging Equipment', subCategory:'MRI', condition:'Refurbished', price:350000, description:'The Hitachi Echelon Oval MRI features the world\'s first oval-shaped bore design, providing unmatched patient comfort with a spacious feel while maintaining 1.5T diagnostic performance. Its zero boil-off magnet technology reduces operational costs significantly.', specs:'{"Field Strength":"1.5 Tesla","Bore Size":"74 cm (oval)","Gradient Strength":"33 mT/m","Slew Rate":"150 T/m/s","Magnet Type":"Zero boil-off superconducting","Coils":"Body, Head, Spine, Extremity","Patient Weight Limit":"500 lbs","Software":"R5.0 workflow suite"}', features:'["Oval bore for maximum patient comfort","Zero boil-off magnet technology","Claustrophobic patient-friendly design","Low operating costs","Parallel imaging (SENS-itivity Encoding)","Comprehensive clinical applications package"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-03-01T10:00:00.000Z' },
  { id:'fp-7', name:'Carestream DRX-Evolution X-Ray', slug:'carestream-drx-evolution-x-ray', category:'X-Ray', parentCategory:'Imaging Equipment', subCategory:'X-Ray', condition:'New', price:125000, description:'The Carestream DRX-Evolution is a versatile digital radiography system designed for high-throughput imaging environments. It features a motorized ceiling-mounted tube stand and wireless DR detectors for flexible positioning.', specs:'{"Generator":"80 kW high-frequency","Tube":"Dual-focus X-ray tube","Detector":"Wireless DRX 3543 (35 x 43 cm)","Detectors Included":"2 wireless panels","Collimation":"Automatic multi-leaf","SID Range":"40-72 inches","Table":"4-way floating tabletop","Software":"Carestream PACS integrated"}', features:'["Wireless DR detector technology","Motorized tube stand positioning","Automatic exposure control (AEC)","Image processing with EVP+ software","DICOM 3.0 worklist management","Bucky wall stand for upright exams"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-03-10T10:00:00.000Z' },
  { id:'fp-8', name:'Canon Aplio i800 Ultrasound', slug:'canon-aplio-i800-ultrasound', category:'Ultrasound', parentCategory:'Imaging Equipment', subCategory:'Ultrasound', condition:'Refurbished', price:88000, description:'The Canon Aplio i800 Ultrasound system delivers premium imaging performance with its iSMC technology and advanced transducer portfolio. It provides exceptional detail resolution and penetration for demanding clinical applications.', specs:'{"Transducer Ports":"3 active ports","Display":"23.8 HD LED monitor","Imaging Modes":"B-mode, Harmonic, Doppler, Elastography","Frame Rate":"Up to 400 fps","Storage":"512 GB SSD","Connectivity":"DICOM, USB, HDMI, Ethernet","Weight":"280 lbs","Channels":"256 digital channels"}', features:'["iSMC micro-scanning technology","Shear Wave elastography","Automated measurements with ApliPure+","Contrast-enhanced ultrasound (CEUS)","Panoramic and 3D/4D imaging","Intelligent workflow automation"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-03-15T10:00:00.000Z' },
  { id:'fp-9', name:'Topcon Maestro 2 OCT', slug:'topcon-maestro-2-oct', category:'Ophthalmology', parentCategory:'Ophthalmology Equipment', subCategory:'OCT', condition:'New', price:68000, description:'The Topcon Maestro 2 is a fully automated, multi-modal diagnostic platform combining OCT, fundus photography, and FA in one compact device. It features swept-source OCT technology for deeper penetration and higher quality retinal images.', specs:'{"OCT Technology":"Swept-source OCT (1,050 nm)","Scan Speed":"50,000 A-scans/second","Axial Resolution":"8 \u03bcm","Scan Width":"12 mm x 9 mm","Fundus Camera":"TrueColor confocal","Visual Fields":"Optional 24-2, 10-2","FA Capability":"Optional fluorescein angiography","Automation":"Fully automated alignment and capture"}', features:'["Swept-source OCT for deeper penetration","Fully automated operation","Combined OCT + fundus camera","Built-in normative database","Single-button multi-modal capture","Compact footprint design"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:true, createdAt:'2025-03-20T10:00:00.000Z' },
  { id:'fp-10', name:'Shimadzu Sonialvision X-Ray', slug:'shimadzu-sonialvision-x-ray', category:'X-Ray', parentCategory:'Imaging Equipment', subCategory:'X-Ray', condition:'Refurbished', price:145000, description:'The Shimadzu Sonialvision is a flat-panel digital radiography and fluoroscopy system designed for multi-purpose diagnostic imaging. It seamlessly handles general radiography, fluoroscopy, and spot imaging in a single system.', specs:'{"Generator":"80 kW high-frequency","Detector":"17 x 17 flat-panel (FPD)","Fluoroscopy":"Real-time digital fluoroscopy","Spot Imaging":"Digital spot radiography","Table":"Multi-directional tilting table","SID Range":"40-60 inches","Dose Management":"SUREexposure technology","Software":"Console with integrated PACS"}', features:'["Flat-panel detector for both R/F","Real-time digital fluoroscopy","Multi-purpose tilting table","Low-dose imaging with SUREexposure","Automatic collimation control","Integrated DICOM connectivity"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-04-01T10:00:00.000Z' },
  { id:'fp-11', name:'GE LOGIQ E10 Ultrasound', slug:'ge-logiq-e10-ultrasound', category:'Ultrasound', parentCategory:'Imaging Equipment', subCategory:'Ultrasound', condition:'New', price:110000, description:'The GE LOGIQ E10 represents the next generation of ultrasound imaging with its revolutionary cSound architecture and high channel count. It delivers extraordinary image clarity and consistency across a wide range of clinical applications.', specs:'{"Transducer Ports":"4 active ports","Display":"23.8 HD LED monitor + 12.1 touchscreen","Architecture":"cSound beamformer","Channels":"128 digital channels","Imaging Modes":"B-mode, Harmonic, Doppler, Strain Elastography","Storage":"1 TB SSD","Connectivity":"DICOM, USB, Wi-Fi, Ethernet","Weight":"330 lbs"}', features:'["cSound architecture for superior imaging","AI-powered image optimization (Auto B-mode)","Strain elastography for tissue characterization","B-Flow and B-Steer technologies","Modern ergonomic design","Comprehensive vascular and cardiac tools"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-04-10T10:00:00.000Z' },
  { id:'fp-12', name:'Heidelberg Spectralis OCT', slug:'heidelberg-spectralis-oct', category:'Ophthalmology', parentCategory:'Ophthalmology Equipment', subCategory:'OCT', condition:'Refurbished', price:58000, description:'The Heidelberg Spectralis OCT is renowned for its proprietary TruTrack active eye-tracking and dual-beam technology that delivers follow-up scans with pixel-perfect reproducibility.', specs:'{"OCT Technology":"Spectral-domain OCT (870 nm)","Scan Speed":"40,000 A-scans/second","Axial Resolution":"3.9 \u03bcm","Transverse Resolution":"14 \u03bcm","Eye Tracking":"TruTrack active eye tracking","Fundus Camera":"Confocal scanning laser ophthalmoscope","FA/ICG":"Optional angiography module","Display":"24 medical-grade monitor"}', features:'["TruTrack dual-beam eye tracking","Pixel-perfect follow-up scanning","BluePeak autofluorescence","OCT-Angiography upgradeable","Anatomical mapping with eye tracking","Widefield imaging module available"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-04-15T10:00:00.000Z' },
  { id:'fp-13', name:'GE Optima XR646 X-Ray', slug:'ge-optima-xr646-x-ray', category:'X-Ray', parentCategory:'Imaging Equipment', subCategory:'X-Ray', condition:'Refurbished', price:92000, description:'The GE Optima XR646 is a reliable digital radiography system built for general-purpose imaging in hospitals and clinics. It features a floor-mounted tube stand and wall stand configuration for maximum flexibility.', specs:'{"Generator":"65 kW high-frequency","Detector":"Wireless 35 x 43 cm DR panel","Tube":"Dual-focus anode","Collimation":"Automatic multi-leaf","SID Range":"40-72 inches","Wall Stand":"Motorized elevating","Table":"4-way floating tabletop","Software":"AutoImage processing suite"}', features:'["AutoImage automatic image processing","Wireless DR detector convenience","Flexible room configurations","DoseWatch dose monitoring","DICOM 3.0 connectivity","Consistent image quality"]', imageUrl:'/images/placeholder-equipment.svg', images:'[]', videos:'[]', status:'active', isFeatured:false, createdAt:'2025-04-20T10:00:00.000Z' },
];

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;

  // Try database first
  try {
    const product = await db.product.findUnique({ where: { slug } });

    if (!product) {
      // Fallback if DB product not found
      const fallback = FALLBACK_PRODUCTS.find((p) => p.slug === slug);
      if (!fallback) {
        return NextResponse.json({ error: 'Product not found' }, { status: 404 });
      }
      const parsed = {
        ...fallback,
        specs: JSON.parse(fallback.specs),
        features: JSON.parse(fallback.features),
        images: JSON.parse(fallback.images || '[]'),
        videos: JSON.parse(fallback.videos || '[]'),
      };
      return NextResponse.json({ product: parsed });
    }

    const parsedProduct = {
      ...product,
      specs: JSON.parse(product.specs || '{}'),
      features: JSON.parse(product.features || '[]'),
      images: JSON.parse(product.images || '[]'),
      videos: JSON.parse(product.videos || '[]'),
    };

    return NextResponse.json({ product: parsedProduct });
  } catch (dbError) {
    // DB unavailable - use fallback
    console.warn('DB unavailable, using fallback for slug:', slug);
    const fallback = FALLBACK_PRODUCTS.find((p) => p.slug === slug);
    if (!fallback) {
      return NextResponse.json({ error: 'Product not found' }, { status: 404 });
    }
    const parsed = {
      ...fallback,
      specs: JSON.parse(fallback.specs),
      features: JSON.parse(fallback.features),
      images: JSON.parse(fallback.images || '[]'),
      videos: JSON.parse(fallback.videos || '[]'),
    };
    return NextResponse.json({ product: parsed });
  }
}
