services:
  - type: web
    name: ps-medical-devices
    runtime: node
    plan: starter
    repo: https://github.com/Chambatina1/Michel.git
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://micel_admin:yJmfj4wjjHF2YHehcvM907wWWb1A8SWM@dpg-d7t6gvl7vvec73ft84qg-a.oregon-postgres.render.com:5432/michel_db?sslmode=require
      - key: DIRECT_DATABASE_URL
        value: postgresql://micel_admin:yJmfj4wjjHF2YHehcvM907wWWb1A8SWM@dpg-d7t6gvl7vvec73ft84qg-a/michel_db?sslmode=require
    healthCheckPath: /
    region: oregon
