import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Import all fallback products directly
const products = [
  {
    name: 'GE Revolution CT Scanner',
    slug: 'ge-revolution-ct-scanner',
    category: 'CT',
    parentCategory: 'Imaging Equipment',
    subCategory: 'CT',
    condition: 'Refurbished',
    price: 185000,
    description: 'The GE Revolution CT Scanner delivers exceptional image quality with its 256-slice detector and advanced iterative reconstruction technology. Designed for high-volume imaging centers, it provides fast turnaround times and reduced dose for patients. This refurbished unit has been fully inspected and calibrated to meet OEM specifications. Ideal for cardiac, neurological, and trauma imaging applications. Comes with a 12-month warranty and on-site installation support.',
    specs: '{"Detector Rows":"256 slices","Rotation Time":"0.28s","Slice Thickness":"0.625 mm","Gantry Aperture":"80 cm","Table Weight Limit":"450 lbs","Tube Heat Capacity":"8.0 MHU","Spatial Resolution":"0.24 mm","Software Version":"Revolution EVO"}',
    features: '["256-slice detector for superior image quality","Advanced iterative reconstruction (ASiR-V)","Low-dose cardiac CT angiography","One-beat cardiac imaging","Automated workflow with kV assist","Smart collimation for dose optimization"]',
    imageUrl: '/images/products/ge-revolution-ct.jpg',
    images: '["/images/products/ge-revolution-ct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Siemens Magnetom Vida 3T MRI',
    slug: 'siemens-magnetom-vida-3t-mri',
    category: 'MRI',
    parentCategory: 'Imaging Equipment',
    subCategory: 'MRI',
    condition: 'Refurbished',
    price: 425000,
    description: 'The Siemens Magnetom Vida 3T MRI combines Tim 4G and Dot technology to deliver outstanding diagnostic confidence across all clinical applications. Its 70 cm bore provides exceptional patient comfort while maintaining high-field performance. This refurbished system features the BioMatrix technology that personalizes exams for each patient. Perfect for neurology, orthopedics, and oncology imaging. Includes comprehensive installation and training package.',
    specs: '{"Field Strength":"3.0 Tesla","Bore Size":"70 cm","Gradient Strength":"45 mT/m","Slew Rate":"200 T/m/s","Channels":"up to 128","Coils":"18-element Body, Head/Neck, Spine","Patient Weight Limit":"550 lbs","Software":"syngo MR XA30"}',
    features: '["Tim 4G integrated coil technology","BioMatrix patient-personalized imaging","70 cm patient-friendly bore","Quiet Suite for reduced acoustic noise","Dot workflow automation","Advanced diffusion and perfusion imaging"]',
    imageUrl: '/images/products/siemens-magnetom-mri.jpg',
    images: '["/images/products/siemens-magnetom-mri.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Philips IU Elite Ultrasound',
    slug: 'philips-iu-elite-ultrasound',
    category: 'Ultrasound',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Ultrasound',
    condition: 'New',
    price: 95000,
    description: 'The Philips IU Elite Ultrasound system is a premium shared-service platform designed for exceptional clinical performance. It features advanced imaging technologies including nSIGHT imaging for enhanced tissue differentiation and PureWave crystal technology for superior resolution. The system excels in abdominal, vascular, OB/GYN, and musculoskeletal imaging.',
    specs: '{"Transducer Ports":"4 active ports","Display":"21.5" HD LCD","Imaging Modes":"B-mode, M-mode, Doppler, Harmonic","Tissue Harmonic":"nSIGHT","Frame Rate":"Up to 300 fps","Storage":"1 TB HDD + DVD-RW","Connectivity":"DICOM 3.0, USB, Ethernet","Weight":"325 lbs"}',
    features: '["nSIGHT imaging for enhanced tissue characterization","PureWave transducer technology","AutoSCAN for automated image optimization","Active Array matrix transducers","QLAB quantitative analysis","iSCAN one-touch image optimization"]',
    imageUrl: '/images/products/philips-iu-elite.jpg',
    images: '["/images/products/philips-iu-elite.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Zeiss Cirrus HD-OCT 6000',
    slug: 'zeiss-cirrus-hd-oct-6000',
    category: 'OCT',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'OCT',
    condition: 'New',
    price: 75000,
    description: 'The Zeiss Cirrus HD-OCT 6000 is the gold standard in optical coherence tomography for ophthalmic diagnostics. It provides ultra-high resolution retinal imaging with advanced segmentation algorithms for retinal nerve fiber layer and ganglion cell analysis. Ideal for glaucoma management, retinal disease assessment, and anterior segment imaging.',
    specs: '{"Scan Speed":"68,000 A-scans/second","Axial Resolution":"5 um","Transverse Resolution":"15 um","Scan Depth":"2.0 mm","Scan Width":"9.0 mm","Imaging Modes":"Macula, Optic Disc, Anterior Segment, HD Angio","Eye Tracking":"TruTrack active","Display":"24" widescreen monitor"}',
    features: '["Ultra-high speed HD imaging","Advanced ganglion cell analysis (GCC)","Glaucoma progression analysis (GPA)","Anterior segment OCT module","HD Angio retinal vasculature imaging","Seamless EMR integration"]',
    imageUrl: '/images/products/zeiss-cirrus-oct.jpg',
    images: '["/images/products/zeiss-cirrus-oct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Toshiba Aquilion ONE CT',
    slug: 'toshiba-aquilion-one-ct',
    category: 'CT',
    parentCategory: 'Imaging Equipment',
    subCategory: 'CT',
    condition: 'Refurbished',
    price: 210000,
    description: 'The Toshiba Aquilion ONE CT Scanner features a 320-row detector that can image an entire organ in a single rotation, reducing motion artifacts and radiation dose significantly. Its cone-beam CT technology eliminates helical artifacts for pure volumetric imaging. Ideal for cardiac, brain perfusion, and whole-organ dynamic studies.',
    specs: '{"Detector Rows":"320 rows (0.5 mm)","Detector Coverage":"16 cm","Rotation Time":"0.275s","Slice Thickness":"0.5 mm","Gantry Aperture":"78 cm","Spatial Resolution":"0.35 mm","Tube Voltage":"80-135 kV","Software":"Vitrea workstation included"}',
    features: '["Volume CT with 16 cm coverage","Single-rotation whole-organ imaging","Ultra-low dose with AIDR 3D","Cardiac CT with 100% phase coverage","Brain perfusion in single rotation","Real-time image reconstruction"]',
    imageUrl: '/images/products/toshiba-aquilion-ct.jpg',
    images: '["/images/products/toshiba-aquilion-ct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Hitachi Echelon Oval MRI',
    slug: 'hitachi-echelon-oval-mri',
    category: 'MRI',
    parentCategory: 'Imaging Equipment',
    subCategory: 'MRI',
    condition: 'Refurbished',
    price: 350000,
    description: 'The Hitachi Echelon Oval MRI features the world\'s first oval-shaped bore design, providing unmatched patient comfort with a spacious feel while maintaining 1.5T diagnostic performance. Its zero boil-off magnet technology reduces operational costs significantly.',
    specs: '{"Field Strength":"1.5 Tesla","Bore Size":"74 cm (oval)","Gradient Strength":"33 mT/m","Slew Rate":"150 T/m/s","Magnet Type":"Zero boil-off superconducting","Coils":"Body, Head, Spine, Extremity","Patient Weight Limit":"500 lbs","Software":"R5.0 workflow suite"}',
    features: '["Oval bore for maximum patient comfort","Zero boil-off magnet technology","Claustrophobic patient-friendly design","Low operating costs","Parallel imaging (SENS-itivity Encoding)","Comprehensive clinical applications package"]',
    imageUrl: '/images/products/hitachi-echelon-mri.jpg',
    images: '["/images/products/hitachi-echelon-mri.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Carestream DRX-Evolution X-Ray',
    slug: 'carestream-drx-evolution-x-ray',
    category: 'X-Ray',
    parentCategory: 'Imaging Equipment',
    subCategory: 'X-Ray',
    condition: 'New',
    price: 125000,
    description: 'The Carestream DRX-Evolution is a versatile digital radiography system designed for high-throughput imaging environments. It features a motorized ceiling-mounted tube stand and wireless DR detectors for flexible positioning.',
    specs: '{"Generator":"80 kW high-frequency","Tube":"Dual-focus X-ray tube","Detector":"Wireless DRX 3543 (35 x 43 cm)","Detectors Included":"2 wireless panels","Collimation":"Automatic multi-leaf","SID Range":"40-72 inches","Table":"4-way floating tabletop","Software":"Carestream PACS integrated"}',
    features: '["Wireless DR detector technology","Motorized tube stand positioning","Automatic exposure control (AEC)","Image processing with EVP+ software","DICOM 3.0 worklist management","Bucky wall stand for upright exams"]',
    imageUrl: '/images/products/carestream-xray.jpg',
    images: '["/images/products/carestream-xray.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Canon Aplio i800 Ultrasound',
    slug: 'canon-aplio-i800-ultrasound',
    category: 'Ultrasound',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Ultrasound',
    condition: 'Refurbished',
    price: 88000,
    description: 'The Canon Aplio i800 Ultrasound system delivers premium imaging performance with its iSMC technology and advanced transducer portfolio. It provides exceptional detail resolution and penetration for demanding clinical applications.',
    specs: '{"Transducer Ports":"3 active ports","Display":"23.8" HD LED monitor","Imaging Modes":"B-mode, Harmonic, Doppler, Elastography","Frame Rate":"Up to 400 fps","Storage":"512 GB SSD","Connectivity":"DICOM, USB, HDMI, Ethernet","Weight":"280 lbs","Channels":"256 digital channels"}',
    features: '["iSMC micro-scanning technology","Shear Wave elastography","Automated measurements with ApliPure+","Contrast-enhanced ultrasound (CEUS)","Panoramic and 3D/4D imaging","Intelligent workflow automation"]',
    imageUrl: '/images/products/canon-aplio-ultrasound.jpg',
    images: '["/images/products/canon-aplio-ultrasound.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Topcon Maestro 2 OCT',
    slug: 'topcon-maestro-2-oct',
    category: 'OCT',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'OCT',
    condition: 'New',
    price: 68000,
    description: 'The Topcon Maestro 2 is a fully automated, multi-modal diagnostic platform combining OCT, fundus photography, and FA in one compact device. It features swept-source OCT technology for deeper penetration and higher quality retinal images.',
    specs: '{"OCT Technology":"Swept-source OCT (1,050 nm)","Scan Speed":"50,000 A-scans/second","Axial Resolution":"8 um","Scan Width":"12 mm x 9 mm","Fundus Camera":"TrueColor confocal","Visual Fields":"Optional 24-2, 10-2","FA Capability":"Optional fluorescein angiography","Automation":"Fully automated alignment and capture"}',
    features: '["Swept-source OCT for deeper penetration","Fully automated operation","Combined OCT + fundus camera","Built-in normative database","Single-button multi-modal capture","Compact footprint design"]',
    imageUrl: '/images/products/topcon-maestro-oct.jpg',
    images: '["/images/products/topcon-maestro-oct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Shimadzu Sonialvision X-Ray',
    slug: 'shimadzu-sonialvision-x-ray',
    category: 'X-Ray',
    parentCategory: 'Imaging Equipment',
    subCategory: 'X-Ray',
    condition: 'Refurbished',
    price: 145000,
    description: 'The Shimadzu Sonialvision is a flat-panel digital radiography and fluoroscopy system designed for multi-purpose diagnostic imaging. It seamlessly handles general radiography, fluoroscopy, and spot imaging in a single system.',
    specs: '{"Generator":"80 kW high-frequency","Detector":"17" x 17" flat-panel (FPD)","Fluoroscopy":"Real-time digital fluoroscopy","Spot Imaging":"Digital spot radiography","Table":"Multi-directional tilting table","SID Range":"40-60 inches","Dose Management":"SUREexposure technology","Software":"Console with integrated PACS"}',
    features: '["Flat-panel detector for both R/F","Real-time digital fluoroscopy","Multi-purpose tilting table","Low-dose imaging with SUREexposure","Automatic collimation control","Integrated DICOM connectivity"]',
    imageUrl: '/images/products/shimadzu-xray.jpg',
    images: '["/images/products/shimadzu-xray.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'GE LOGIQ E10 Ultrasound',
    slug: 'ge-logiq-e10-ultrasound',
    category: 'Ultrasound',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Ultrasound',
    condition: 'New',
    price: 110000,
    description: 'The GE LOGIQ E10 represents the next generation of ultrasound imaging with its revolutionary cSound architecture and high channel count. It delivers extraordinary image clarity and consistency across a wide range of clinical applications.',
    specs: '{"Transducer Ports":"4 active ports","Display":"23.8" HD LED monitor + 12.1" touchscreen","Architecture":"cSound beamformer","Channels":"128 digital channels","Imaging Modes":"B-mode, Harmonic, Doppler, Strain Elastography","Storage":"1 TB SSD","Connectivity":"DICOM, USB, Wi-Fi, Ethernet","Weight":"330 lbs"}',
    features: '["cSound architecture for superior imaging","AI-powered image optimization (Auto B-mode)","Strain elastography for tissue characterization","B-Flow and B-Steer technologies","Modern ergonomic design","Comprehensive vascular and cardiac tools"]',
    imageUrl: '/images/products/ge-logiq-e10.jpg',
    images: '["/images/products/ge-logiq-e10.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Heidelberg Spectralis OCT',
    slug: 'heidelberg-spectralis-oct',
    category: 'OCT',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'OCT',
    condition: 'Refurbished',
    price: 58000,
    description: 'The Heidelberg Spectralis OCT is renowned for its proprietary TruTrack active eye-tracking and dual-beam technology that delivers follow-up scans with pixel-perfect reproducibility. It is the preferred choice for longitudinal monitoring of retinal diseases.',
    specs: '{"OCT Technology":"Spectral-domain OCT (870 nm)","Scan Speed":"40,000 A-scans/second","Axial Resolution":"3.9 um","Transverse Resolution":"14 um","Eye Tracking":"TruTrack active eye tracking","Fundus Camera":"Confocal scanning laser ophthalmoscope","FA/ICG":"Optional angiography module","Display":"24" medical-grade monitor"}',
    features: '["TruTrack dual-beam eye tracking","Pixel-perfect follow-up scanning","BluePeak autofluorescence","OCT-Angiography upgradeable","Anatomical mapping with eye tracking","Widefield imaging module available"]',
    imageUrl: '/images/products/heidelberg-spectralis-oct.jpg',
    images: '["/images/products/heidelberg-spectralis-oct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'GE Optima XR646 X-Ray',
    slug: 'ge-optima-xr646-x-ray',
    category: 'X-Ray',
    parentCategory: 'Imaging Equipment',
    subCategory: 'X-Ray',
    condition: 'Refurbished',
    price: 92000,
    description: 'The GE Optima XR646 is a reliable digital radiography system built for general-purpose imaging in hospitals and clinics. It features a floor-mounted tube stand and wall stand configuration for maximum flexibility.',
    specs: '{"Generator":"65 kW high-frequency","Detector":"Wireless 35 x 43 cm DR panel","Tube":"Dual-focus anode","Collimation":"Automatic multi-leaf","SID Range":"40-72 inches","Wall Stand":"Motorized elevating","Table":"4-way floating tabletop","Software":"AutoImage processing suite"}',
    features: '["AutoImage automatic image processing","Wireless DR detector convenience","Flexible room configurations","DoseWatch dose monitoring","DICOM 3.0 connectivity","Consistent image quality"]',
    imageUrl: '/images/products/ge-optima-xray.jpg',
    images: '["/images/products/ge-optima-xray.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Siemens SOMATOM Force CT Scanner',
    slug: 'siemens-somatom-force-ct',
    category: 'CT',
    parentCategory: 'Imaging Equipment',
    subCategory: 'CT',
    condition: 'Refurbished',
    price: 295000,
    description: 'The Siemens SOMATOM Force is a dual-source CT scanner offering unmatched speed and spatial resolution. With its Stellar Infinity detector and Tin Filter technology, it delivers ultra-low dose imaging across all clinical applications.',
    specs: '{"Source":"Dual-source (2 x 120 kW)","Detector":"Stellar Infinity","Slice":"0.25 mm","Rotation":"0.25s","TSA":"78 cm","Dose":"SAFIRE + Tin Filter"}',
    features: '["Dual-source for maximum speed","Stellar Infinity detector","Tin Filter ultra-low dose","0.25s rotation time","Cardiac CT without beta-blockers","Pediatric-friendly low dose"]',
    imageUrl: '/images/products/siemens-somatom-ct.jpg',
    images: '["/images/products/siemens-somatom-ct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Philips Ingenia Ambition 1.5T MRI',
    slug: 'philips-ambition-1-5t-mri',
    category: 'MRI',
    parentCategory: 'Imaging Equipment',
    subCategory: 'MRI',
    condition: 'Refurbished',
    price: 385000,
    description: 'The Philips Ingenia Ambition 1.5T MRI features BlueSeal magnet technology, making it the most environmentally friendly MRI on the market. Its dStream broadband architecture delivers outstanding image quality with up to 40% faster scans.',
    specs: '{"Field":"1.5 Tesla","Bore":"70 cm","Magnet":"BlueSeal (no helium refill)","Gradient":"45 mT/m","Channels":"up to 120","Coils":"dStream digital","Software":"Ingenia OS 5.4"}',
    features: '["BlueSeal zero-helium-boil-off magnet","dStream broadband digital","70 cm wide bore","Compressed SENSE acceleration","Multi-transmit technology","Eco-friendly operation"]',
    imageUrl: '/images/products/philips-ambition-mri.jpg',
    images: '["/images/products/philips-ambition-mri.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Hologic Selenia Dimensions Mammography',
    slug: 'hologic-selenia-dimensions-mammography',
    category: 'Mammography',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Mammography',
    condition: 'Refurbished',
    price: 165000,
    description: 'The Hologic Selenia Dimensions is the leading full-field digital mammography system with tomosynthesis (3D) capability. It delivers exceptional image quality for early breast cancer detection.',
    specs: '{"Detector":"DirectCapture amorphous selenium","Resolution":"70 micron pixel","3D":"Tomosynthesis capable","Compression":"Intelligent Auto-Compression","Bucky":"Tilting","Software":"Dimensions 7.0"}',
    features: '["3D breast tomosynthesis","Intelligent compression technology","70 micron resolution","Breast density assessment","Contrast-enhanced mammography","Biopsy guidance compatible"]',
    imageUrl: '/images/products/hologic-mammography.jpg',
    images: '["/images/products/hologic-mammography.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'GE Vivid E95 Cardiovascular Ultrasound',
    slug: 'ge-vivid-e95-ultrasound',
    category: 'Ultrasound',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Ultrasound',
    condition: 'New',
    price: 135000,
    description: 'The GE Vivid E95 is a premium cardiovascular ultrasound system featuring cSound architecture and advanced quantification tools. It delivers exceptional 4D cardiac imaging with automated strain analysis.',
    specs: '{"Architecture":"cSound","Display":"23.8" HD + 12.1" touch","Transducers":"Cardiac suite included","4D":"Real-time 4D echo","Strain":"AFI automated","Storage":"512 GB SSD"}',
    features: '["cSound architecture","cFace facial recognition auto-optimization","4D volume imaging","Automated Function Imaging (AFI)","LV quantification with AutoEF","Cardiac stress echo capable"]',
    imageUrl: '/images/products/ge-vivid-e95.jpg',
    images: '["/images/products/ge-vivid-e95.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Topcon TRC-50DX Retinal Camera',
    slug: 'topcon-trc-50dx-retinal-camera',
    category: 'Retinal Camera',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Retinal Camera',
    condition: 'New',
    price: 22000,
    description: 'The Topcon TRC-50DX is a high-resolution non-mydriatic retinal camera that captures detailed fundus images without pupil dilation. It features a 20-megapixel sensor and built-in auto-focus for effortless operation.',
    specs: '{"Sensor":"20 megapixel CCD","Angle":"50 degrees field of view","Flash":"LED + Xenon","Focus":"Auto-focus","Non-Mydriatic":"Yes (pupil size 3.3mm+)","Image":"JPEG, BMP, DICOM"}',
    features: '["Non-mydriatic operation","20MP high-resolution sensor","Auto-focus and auto-exposure","DICOM connectivity","Compact desktop design","Wide-angle 50-degree view"]',
    imageUrl: '/images/products/topcon-retinal-camera.jpg',
    images: '["/images/products/topcon-retinal-camera.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Nidek RS-3000 Advance OCT',
    slug: 'nidek-rs3000-advance-oct',
    category: 'OCT',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'OCT',
    condition: 'Refurbished',
    price: 42000,
    description: 'The Nidek RS-3000 Advance is a spectral-domain OCT system offering high-resolution retinal imaging with an ergonomic design. It provides detailed retinal nerve fiber layer analysis and ganglion cell complex mapping.',
    specs: '{"Technology":"SD-OCT (880 nm)","Speed":"53,000 A-scans/sec","Axial Res":"7 um","Scan Width":"12 x 9 mm","RNFL":"Automated analysis","GCC":"Ganglion cell complex"}',
    features: '["High-speed SD-OCT","Comprehensive RNFL analysis","Ganglion cell complex mapping","Choroidal thickness measurement","Automated segmentation","User-friendly touchscreen"]',
    imageUrl: '/images/products/nidek-oct.jpg',
    images: '["/images/products/nidek-oct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Philips Veradius C-Arm',
    slug: 'philips-veradius-c-arm',
    category: 'C-Arm',
    parentCategory: 'Imaging Equipment',
    subCategory: 'C-Arm',
    condition: 'Refurbished',
    price: 85000,
    description: 'The Philips Veradius is a compact and powerful C-arm fluoroscopy system designed for surgical and interventional procedures. It features a flat-panel detector for superior image quality and advanced dose management.',
    specs: '{"Generator":"15 kW","Detector":"30 x 30 cm flat panel","Resolution":"2K x 2K","Movement":"Motorized orbital","Display":"3 monitors included","Dose":"DoseAware technology"}',
    features: '["Flat-panel detector technology","Compact design for OR","Motorized orbital movement","DoseAware dose management","3D rotational angiography","DICOM 3.0 connectivity"]',
    imageUrl: '/images/products/philips-carm.jpg',
    images: '["/images/products/philips-carm.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Hologic Horizon DXA Bone Densitometer',
    slug: 'hologic-horizon-dxa',
    category: 'DXA',
    parentCategory: 'Imaging Equipment',
    subCategory: 'DXA',
    condition: 'Refurbished',
    price: 55000,
    description: 'The Hologic Horizon DXA is a dual-energy X-ray absorptiometry system for bone density measurement and body composition analysis. It provides precise osteoporosis assessment with instant VFA.',
    specs: '{"Technology":"Fan-beam DXA","Scan Time":"30 seconds (spine/hip)","Dose":"Ultra-low (micro-Sv)","VFA":"Instant vertebral fracture assess","Analysis":"FRAX integration","Table":"Low-profile, wide opening"}',
    features: '["Fast 30-second scans","Ultra-low radiation dose","Instant VFA assessment","Body composition analysis","FRAX fracture risk integration","ADA-compliant low-profile table"]',
    imageUrl: '/images/products/hologic-dxa.jpg',
    images: '["/images/products/hologic-dxa.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Mindray DC-80 Ultrasound',
    slug: 'mindray-dc80-ultrasound',
    category: 'Ultrasound',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Ultrasound',
    condition: 'New',
    price: 65000,
    description: 'The Mindray DC-80 is a high-performance shared-service ultrasound system offering premium imaging at an exceptional value. It features advanced technologies including ZONE Sonography, Auto IMT, and 3D/4D imaging.',
    specs: '{"Display":"21.5" HD LED","Transducers":"3 active ports","3D/4D":"Real-time","Channels":"256 digital","Imaging":"ZONE Sonography","Storage":"500 GB HDD"}',
    features: '["ZONE Sonography technology","3D/4D real-time imaging","Auto IMT measurement","iTouch one-key optimization","Comprehensive reporting","Affordable premium quality"]',
    imageUrl: '/images/products/mindray-dc80.jpg',
    images: '["/images/products/mindray-dc80.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Toshiba Vantage Elan 1.5T MRI',
    slug: 'toshiba-vantage-elan-1-5t-mri',
    category: 'MRI',
    parentCategory: 'Imaging Equipment',
    subCategory: 'MRI',
    condition: 'Refurbished',
    price: 275000,
    description: 'The Toshiba Vantage Elan 1.5T MRI features Atlas SPEEDER parallel imaging and Pianissimo Zen quiet technology for an exceptionally quiet scan experience. Its 71 cm bore and short magnet design maximize patient comfort.',
    specs: '{"Field":"1.5 Tesla","Bore":"71 cm","Gradient":"33 mT/m","Slew":"177 T/m/s","Quiet":"Pianissimo Zen","Coils":"8-channel body array included"}',
    features: '["71 cm ultra-wide bore","Pianissimo Zen quiet technology","Atlas SPEEDER parallel imaging","Short magnet design","Ergonomic patient table","Comprehensive clinical apps"]',
    imageUrl: '/images/products/toshiba-vantage-mri.jpg',
    images: '["/images/products/toshiba-vantage-mri.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Zeiss IOLMaster 700 Optical Biometer',
    slug: 'zeiss-iolmaster-700-biometer',
    category: 'Refractometers',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Refractometers',
    condition: 'New',
    price: 48000,
    description: 'The Zeiss IOLMaster 700 is the gold standard in optical biometry for cataract surgery planning. It uses swept-source OCT technology for highly accurate axial length measurements, even with dense cataracts.',
    specs: '{"Technology":"Swept-source OCT (1050 nm)","Axial Length Accuracy":"0.01 mm","Keratometry":"9-zone total","ACD":"Automated measurement","Lens Thickness":"Automated","IOL Formulas":"Barrett, Hill-RBF, Haigis, SRK/T"}',
    features: '["Swept-source OCT biometry","Accuracy through dense cataracts","9-zone total keratometry","Automated measurements","Comprehensive IOL formulas","Touchscreen workflow"]',
    imageUrl: '/images/products/zeiss-iolmaster.jpg',
    images: '["/images/products/zeiss-iolmaster.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: true,
  },
  {
    name: 'Haag-Streit BQ 900 Slit Lamp',
    slug: 'haag-streit-bq900-slit-lamp',
    category: 'Examination',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Examination',
    condition: 'New',
    price: 9800,
    description: 'The Haag-Streit BQ 900 is a premium slit lamp biomicroscope renowned for its exceptional optical quality and precision engineering. It provides detailed anterior segment examination for diagnosis of corneal, lens, and iris pathologies.',
    specs: '{"Magnification":"5-step (6.3x, 10x, 16x, 25x, 40x)","Illumination":"LED (50,000 Lux)","Slit":"11 adjustable apertures","Filter":"Red-free, cobalt blue, heat-absorbing","Mount":"Table mount with base","Eyepieces":"Wide-field 12.5x"}',
    features: '["LED illumination (long-lasting, cool)","5-step Galilean magnification","Precision Swiss optics","Smooth joystick control","Multiple slit apertures","Digital imaging compatible"]',
    imageUrl: '/images/products/haag-streit-slitlamp.jpg',
    images: '["/images/products/haag-streit-slitlamp.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Oculus Easyfield Perimeter',
    slug: 'oculus-easyfield-perimeter',
    category: 'Visual Field',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Visual Field',
    condition: 'Refurbished',
    price: 15000,
    description: 'The Oculus Easyfield is a compact visual field analyzer that delivers fast and reliable perimetry testing for glaucoma and neurological assessment. The compact design makes it ideal for small practices and screening environments.',
    specs: '{"Stimulus":"Goldmann III (31.5 asb)","Background":"10 cd/m2","Strategies":"Full threshold, 2-phase, screening","Range":"Full field up to 30 degrees","Fixation":"LED blind-spot monitoring","Display":"Color LCD screen"}',
    features: '["Compact desktop design","Goldmann III stimulus","Multiple test strategies","LED fixation monitoring","Fast threshold testing","Built-in analysis software"]',
    imageUrl: '/images/products/oculus-visual-field.jpg',
    images: '["/images/products/oculus-visual-field.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Fujifilm FDR Flex Digital X-Ray',
    slug: 'fujifilm-fdr-flex-xray',
    category: 'X-Ray',
    parentCategory: 'Imaging Equipment',
    subCategory: 'X-Ray',
    condition: 'New',
    price: 115000,
    description: 'The Fujifilm FDR Flex is a versatile direct digital radiography system offering floor-mounted tube stand and wall stand configurations. It features Fujifilm\'s renowned image processing with RE technology.',
    specs: '{"Generator":"80 kW high-frequency","Detector":"FDR D-EVO II 35x43 cm wireless","Processing":"RE technology + ISS","Collimation":"Automatic multi-leaf","Wall Stand":"Motorized elevating","Software":"Fujifilm Synapse PACS ready"}',
    features: '["FDR flat-panel detector","RE resolution enhancement","ISS intelligent stitching","Wireless panel freedom","Automatic exposure control","Synapse PACS integration"]',
    imageUrl: '/images/products/fujifilm-xray.jpg',
    images: '["/images/products/fujifilm-xray.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Canon Auto Keratometer RK-5',
    slug: 'canon-rk5-auto-keratometer',
    category: 'Refractometers',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Refractometers',
    condition: 'New',
    price: 7500,
    description: 'The Canon RK-5 Auto Keratometer / Refractometer combines automated keratometry and refractometry in one compact unit. It provides fast, accurate measurements of corneal curvature and refractive error.',
    specs: '{"Keratometry Range":"5.0-10.0 mm (33.75-67.5D)","Refractometry":"Sphere +/-20D, Cylinder +/-8D","PD Measurement":"30-85 mm","IOL Mode":"Yes","Display":"Color LCD","Print":"Thermal printer built-in"}',
    features: '["Combined keratometry + refractometry","One-touch measurement","IOL calculation mode","Wide measurement range","Built-in thermal printer","Compact desktop design"]',
    imageUrl: '/images/products/canon-refractometer.jpg',
    images: '["/images/products/canon-refractometer.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Haufe Visucam 524 Fundus Camera',
    slug: 'haufe-visucam-524-fundus-camera',
    category: 'Retinal Camera',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Retinal Camera',
    condition: 'Refurbished',
    price: 18000,
    description: 'The Haufe Visucam 524 is a non-mydriatic fundus camera providing high-quality color fundus photography with optional fluorescein angiography and ICG capabilities.',
    specs: '{"Sensor":"8 megapixel CCD","Field of View":"45 degrees","Flash":"Xenon","Non-Mydriatic":"Yes (3.5mm pupil)","FA":"Optional fluorescein angiography","ICG":"Optional ICG angiography"}',
    features: '["Non-mydriatic fundus photography","High-resolution 8MP images","Auto-focus and auto-exposure","Optional FA/ICG angiography","DICOM connectivity","Ergonomic joystick operation"]',
    imageUrl: '/images/products/haufe-visucam.jpg',
    images: '["/images/products/haufe-visucam.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'GE Discovery RT CT Simulator',
    slug: 'ge-discovery-rt-ct-simulator',
    category: 'CT',
    parentCategory: 'Imaging Equipment',
    subCategory: 'CT',
    condition: 'Refurbished',
    price: 250000,
    description: 'The GE Discovery RT is a 16-slice CT simulator optimized for radiation therapy planning. It features a large 80 cm bore for oncology patient positioning and 4D respiratory gating capabilities.',
    specs: '{"Slices":"16","Bore":"80 cm","4D Gating":"Respiratory gating capable","Laser":"External laser positioning","Table":"Flat carbon fiber RT table","Software":"Advantage Sim 6.0"}',
    features: '["Large 80 cm bore","4D respiratory gating","RT-specific table","Laser positioning system","Integrated with major TPS","Oncology-optimized protocols"]',
    imageUrl: '/images/products/ge-revolution-ct.jpg',
    images: '["/images/products/ge-revolution-ct.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Siemens Artis Zee C-Arm',
    slug: 'siemens-artis-zee-c-arm',
    category: 'C-Arm',
    parentCategory: 'Imaging Equipment',
    subCategory: 'C-Arm',
    condition: 'Refurbished',
    price: 120000,
    description: 'The Siemens Artis Zee is a premium flat-panel C-arm system for interventional radiology and cardiac catheterization. It provides outstanding image quality with low dose technology.',
    specs: '{"Generator":"20 kW","Detector":"30 x 40 cm flat panel","Resolution":"2K x 2K","Movement":"Motorized C-arm","Display":"3 monitors","Dose":"CARE + CLEAR technology"}',
    features: '["Flat-panel detector technology","Motorized C-arm movement","CARE dose reduction","CLEAR image enhancement","3D rotational angiography","Syngo workstation integration"]',
    imageUrl: '/images/products/philips-carm.jpg',
    images: '["/images/products/philips-carm.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Mindray Resona R9 Ultrasound',
    slug: 'mindray-resona-r9-ultrasound',
    category: 'Ultrasound',
    parentCategory: 'Imaging Equipment',
    subCategory: 'Ultrasound',
    condition: 'New',
    price: 92000,
    description: 'The Mindray Resona R9 is a premium ultrasound system featuring ZONE Sonography Technology+ (ZST+) for exceptional image quality across all clinical applications.',
    specs: '{"Display":"23.8" HD LED","Transducers":"4 active ports","Channels":"512 digital","3D/4D":"Real-time","Storage":"1 TB SSD","Connectivity":"DICOM, USB, Wi-Fi"}',
    features: '["ZST+ advanced imaging","512 digital channels","3D/4D real-time imaging","Auto workflow tools","iTouch optimization","Comprehensive transducer suite"]',
    imageUrl: '/images/products/mindray-dc80.jpg',
    images: '["/images/products/mindray-dc80.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
  {
    name: 'Topcon KR-800 Auto Refractor',
    slug: 'topcon-kr800-auto-refractor',
    category: 'Refractometers',
    parentCategory: 'Ophthalmology Equipment',
    subCategory: 'Refractometers',
    condition: 'New',
    price: 8200,
    description: 'The Topcon KR-800 is a precision auto refractor/keratometer designed for fast, accurate measurements. It features rotary prism technology and SLD alignment indicator.',
    specs: '{"Measurement Range":"S: -20 to +20D, C: 0 to +/-8D","Keratometry":"5.0-10.0 mm","PD":"30-85 mm","IOL Mode":"Yes","Display":"Color LCD","Print":"Thermal printer"}',
    features: '["Rotary prism technology","SLD alignment indicator","IOL calculation mode","Fast measurement","Reliable accuracy","Compact design"]',
    imageUrl: '/images/products/canon-refractometer.jpg',
    images: '["/images/products/canon-refractometer.jpg"]',
    videos: '[]',
    status: 'active',
    isFeatured: false,
  },
];

async function main() {
  console.log(`Importing ${products.length} products into database...`);

  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (const product of products) {
    try {
      // Check if product already exists by slug
      const existing = await prisma.product.findUnique({
        where: { slug: product.slug },
      });

      if (existing) {
        // Update existing product instead of skipping
        await prisma.product.update({
          where: { slug: product.slug },
          data: product,
        });
        console.log(`  Updated: ${product.name}`);
        skipped++;
      } else {
        await prisma.product.create({ data: product });
        console.log(`  Created: ${product.name}`);
        created++;
      }
    } catch (error) {
      console.error(`  Error with ${product.name}:`, error);
      errors++;
    }
  }

  console.log(`\nDone! Created: ${created}, Updated: ${skipped}, Errors: ${errors}`);

  // Count total products in DB
  const total = await prisma.product.count();
  console.log(`Total products in database: ${total}`);

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  prisma.$disconnect();
  process.exit(1);
});
